### ISSUE TITLE
Package uses not-fully correct TOML input in examples

### ISSUE THREAD

**Issue by eddelbuettel** [Miachol/configr#5]
[configr](https://github.com/Miachol/configr/) has long relied on my [RcppTOML](https://github.com/eddelbuettel/rcpptoml) package for parsing TOML. [RcppTOML](https://github.com/eddelbuettel/rcpptoml) is built around [cpptoml](https://github.com/skystrife/cpptoml) by Chase Geigle, and it unfortunately stuck to version 0.5.0 of the TOML spec and is no longer maintained.  I built a replacement package [RcppTomlPlusPlus](https://github.com/eddelbuettel/rcpptomlplusplus) around the newer [toml++](https://github.com/marzer/tomlplusplus) library which is TOML 1.0.0 compliant. 

I have a branch on [RcppTOML](https://github.com/eddelbuettel/rcpptoml) where I folded [RcppTomlPlusPlus](https://github.com/eddelbuettel/rcpptomlplusplus) in, this could go to CRAN as it is a feature-by-feature complete replacement.  I have run the reverse-depends, and all CRAN reverse dependencies of [RcppTOML](https://github.com/eddelbuettel/rcpptoml) pass with this candidate package.   Apart from [configr](https://github.com/Miachol/configr/) which is why I opened this issue.

In debugging what may cause this I found that it is not an error in [configr](https://github.com/Miachol/configr/) per se but rather in the data file use throughout. These lines 

https://github.com/JhuangLab/BioInstaller/blob/01464c1dca00defdbbe2ac77fc18b0661c24070e/inst/extdata/config/db/db_annovar.toml#L329-L331

use keys containing `++` which, according to [the TOML spec](https://toml.io/en/v1.0.0#keyvalue-pair) is not allowed: they need to be quote enclosed.  You can test that with a simple input file

```toml
[db_annovar_gerp.buildver_available]
grep++elem = ["hg19", "hg18", "mm9"]
gerp++gt2 = ["hg19", "hg18"]
```

which will fail under [RcppTomlPlusPlus](https://github.com/eddelbuettel/rcpptomlplusplus) using the TOML 1.0 compliant [toml++](https://github.com/marzer/tomlplusplus) parse but once you change to

```toml
[db_annovar_gerp.buildver_available]
"grep++elem" = ["hg19", "hg18", "mm9"]
"gerp++gt2" = ["hg19", "hg18"]
```

it passes just fine. Note that even GitHub here renders the invalid key=value pair in red.

There are two possible fixes.  As the (fixed, apparently) input file in the copy of [BioInstaller](https://github.com/JhuangLab/BioInstaller) is apparently also last changed by you, you could just make this edit of embedding two keys in quotes.  Alternatively, one can switch from `db_annovar` to, say, `db_blast` as I have done in patched version. It too passes all tests, and I would be happy to send you a PR if you could send this to CRAN.

Please let me know what you think, and if you could accomodate this change on your side facilitating an upgrade of [RcppTOML](https://github.com/eddelbuettel/rcpptoml).

Edit: For completeness I include the diff below. Happy to submit as a PR.

<details>

```diff
diff -ru configr.orig/inst/doc/configr.R configr/inst/doc/configr.R
--- configr.orig/inst/doc/configr.R	2020-07-17 04:24:13.000000000 -0500
+++ configr/inst/doc/configr.R	2023-01-08 10:56:18.840153411 -0600
@@ -44,7 +44,7 @@
 eval.config.merge(file = config.toml, sections = c('default', 'comments'))
 
 ## ---- echo = TRUE-------------------------------------------------------------
-links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml", 
+links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_blast.toml",
            "https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml", 
            system.file('extdata', 'config.toml', package = "configr"))
 x <- fetch.config(links)
diff -ru configr.orig/inst/doc/configr.Rmd configr/inst/doc/configr.Rmd
--- configr.orig/inst/doc/configr.Rmd	2020-07-17 01:18:43.000000000 -0500
+++ configr/inst/doc/configr.Rmd	2023-01-08 10:56:26.736083808 -0600
@@ -93,7 +93,7 @@
 `fetch.config` can parse configuration files from internet and local that merged the files and return a list.
 
 ```{r, echo = TRUE}
-links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml", 
+links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_blast.toml", 
            "https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml", 
            system.file('extdata', 'config.toml', package = "configr"))
 x <- fetch.config(links)
diff -ru configr.orig/man/fetch.config.Rd configr/man/fetch.config.Rd
--- configr.orig/man/fetch.config.Rd	2020-07-17 03:54:31.000000000 -0500
+++ configr/man/fetch.config.Rd	2023-01-08 10:56:04.088283417 -0600
@@ -35,7 +35,7 @@
 }
 \examples{
 links <- c(paste0('https://raw.githubusercontent.com/JhuangLab', 
-'/BioInstaller/master/inst/extdata/config/db/db_annovar.toml'), 
+'/BioInstaller/master/inst/extdata/config/db/db_blast.toml'), 
 paste0('https://raw.githubusercontent.com/JhuangLab/BioInstaller', 
 '/master/inst/extdata/config/db/db_main.toml'), 
 system.file('extdata', 'config.toml', package = 'configr'))
diff -ru configr.orig/R/fetch.R configr/R/fetch.R
--- configr.orig/R/fetch.R	2020-07-17 01:18:43.000000000 -0500
+++ configr/R/fetch.R	2023-01-08 10:56:11.520217924 -0600
@@ -13,7 +13,7 @@
 #' @export
 #' @examples
 #' links <- c(paste0('https://raw.githubusercontent.com/JhuangLab', 
-#' '/BioInstaller/master/inst/extdata/config/db/db_annovar.toml'), 
+#' '/BioInstaller/master/inst/extdata/config/db/db_blast.toml'),
 #' paste0('https://raw.githubusercontent.com/JhuangLab/BioInstaller', 
 #' '/master/inst/extdata/config/db/db_main.toml'), 
 #' system.file('extdata', 'config.toml', package = 'configr'))
diff -ru configr.orig/README.md configr/README.md
--- configr.orig/README.md	2020-07-17 01:18:43.000000000 -0500
+++ configr/README.md	2023-01-08 10:55:54.384368913 -0600
@@ -102,7 +102,7 @@
 yaml_config <- str2config(yaml_string)
 
 # Read configuration files from remote sits
-links <- c('https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml', 
+links <- c('https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_blast.toml', 
            'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml')
 fetch.config(links)
 
Only in configr/tests/testthat: _snaps
diff -ru configr.orig/tests/testthat/test_m_fetch.R configr/tests/testthat/test_m_fetch.R
--- configr.orig/tests/testthat/test_m_fetch.R	2020-07-17 01:18:43.000000000 -0500
+++ configr/tests/testthat/test_m_fetch.R	2023-01-08 10:55:29.248590284 -0600
@@ -1,6 +1,6 @@
 test_that("fetch.config", {
-  links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml", 
-    "https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml", 
+  links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_blast.toml",
+      "https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml",
     system.file("extdata", "config.toml", package = "configr"))
   x <- fetch.config(links)
   expect_that(is.list(x), equals(TRUE))
diff -ru configr.orig/vignettes/configr.Rmd configr/vignettes/configr.Rmd
--- configr.orig/vignettes/configr.Rmd	2020-07-17 01:18:43.000000000 -0500
+++ configr/vignettes/configr.Rmd	2023-01-08 10:56:37.719986967 -0600
@@ -93,7 +93,7 @@
 `fetch.config` can parse configuration files from internet and local that merged the files and return a list.
 
 ```{r, echo = TRUE}
-links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml", 
+links <- c("https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_blast.toml", 
            "https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml", 
            system.file('extdata', 'config.toml', package = "configr"))
 x <- fetch.config(links)
```

</details>

**Comment by Miachol** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Prof. Eddelbuettel,Thank you for your feedback. I have edited the db_annovar.toml file in BioInstaller package: the quotes were added. I hope this change could make RcppTOML pass CRAN tests.Best wishes,Jianfeng
    
        
            
        
    
    
        
        

        
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Dirk ***@***.***>
            
        
      
      
        
         Date 
        
        
        1/9/2023 01:23
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [Miachol/configr] Package uses not-fully correct TOML input in examples (Issue #5)
        
      
    
  
  
configr has long relied on my RcppTOML package for parsing TOML. RcppTOML is built around cpptoml by Chase Geigle, and it unfortunately stuck to version 0.5.0 of the TOML spec and is no longer maintained.  I built a replacement package RcppTomlPlusPlus around the newer toml++ library which is TOML 1.0.0 compliant.
I have a branch on RcppTOML where I folded RcppTomlPlusPlus in, this could go to CRAN as it is a feature-by-feature complete replacement.  I have run the reverse-depends, and all CRAN reverse dependencies of RcppTOML pass with this candidate package.   Apart from configr which is why I opened this issue.
In debugging what may cause this I found that it is not an error in configr per se but rather in the data file use throughout. These lines
https://github.com/JhuangLab/BioInstaller/blob/01464c1dca00defdbbe2ac77fc18b0661c24070e/inst/extdata/config/db/db_annovar.toml#L329-L331
use keys containing ++ which, according to the TOML spec is not allowed: they need to be quote enclosed.  You can test that with a simple input file
[db_annovar_gerp.buildver_available]
grep++elem = ["hg19", "hg18", "mm9"]
gerp++gt2 = ["hg19", "hg18"]
which will fail under RcppTomlPlusPlus using the TOML 1.0 compliant toml++ parse but once you change to
[db_annovar_gerp.buildver_available]
"grep++elem" = ["hg19", "hg18", "mm9"]
"gerp++gt2" = ["hg19", "hg18"]
it passes just fine. Note that even GitHub here renders the invalid key=value pair in red.
There are two possible fixes.  As the (fixed, apparently) input file in the copy of BioInstaller is apparently also last changed by you, you could just make this edit of embedding two keys in quotes.  Alternatively, one can switch from db_annovar to, say, db_blast as I have done in patched version. It too passes all tests, and I would be happy to send you a PR if you could send this to CRAN.
Please let me know what you think, and if you could accomodate this change on your side facilitating an upgrade of RcppTOML.

**Comment by eddelbuettel** [comment]
Thank you so much for the very speed reply!  I can confirm that this allows the CRAN version of `configr` to test with the 'pending' and enhanced version of `RcppTOML` using the more stringent parser:

```sh
edd@rob:/tmp/configr/configr.orig$ Rscript -e 'library(configr); testthat::test_file("tests/testthat/test_m_fetch.R")'

══ Testing test_m_fetch.R ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml'
Content type 'text/plain; charset=utf-8' length 42979 bytes (41 KB)
==================================================
downloaded 41 KB

trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml'
Content type 'text/plain; charset=utf-8' length 35027 bytes (34 KB)
==================================================
downloaded 34 KB

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ]trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml'
Content type 'text/plain; charset=utf-8' length 42979 bytes (41 KB)
==================================================
downloaded 41 KB

trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml'
Content type 'text/plain; charset=utf-8' length 35027 bytes (34 KB)
==================================================
downloaded 34 KB

trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_annovar.toml'
Content type 'text/plain; charset=utf-8' length 42979 bytes (41 KB)
==================================================
downloaded 41 KB

trying URL 'https://raw.githubusercontent.com/JhuangLab/BioInstaller/master/inst/extdata/config/db/db_main.toml'
Content type 'text/plain; charset=utf-8' length 35027 bytes (34 KB)
==================================================
downloaded 34 KB

 Done!
edd@rob:/tmp/configr/configr.orig$

```

I think this addresses the issue here as the test input was amended, so I close this.  Thanks again!
